#!/bin/bash



#Author : Vrshu
#Date :20-1-2024
#Version : v1



#This script will report the AWS resource usage.


set -x
#AWS s3
#AWS EC2
#AWS Lambda
#AWS IAM Users



#list the s3 Buckets
echo "Print list of S3 Buckets"
aws s3 ls


#list the EC2 instances
echo "Print list of EC2 Instances"
aws ec2 describe-instances --region eu-west-3 --query "Reservations[].Instances[].InstanceId[]"



#list aws lambda
echo "Print list of Lambda Functions"
aws lambda list-functions


#list IAM Users
echo "Print list of IAM Users"
aws iam list-users
